#!/bin/bash
clear;echo "##########################################"
echo -e "   Auto installer Vmess akun\n##########################################\n"
echo "Installing, Tunggu.....";opkg update 2>/dev/null && opkg install coreutils-base64 coreutils-timeout curl
wget -O /usr/bin/vmess https://raw.githubusercontent.com/ryanfauzi1/vmesscreator/main/vmess;chmod +x /usr/bin/vmess;clear
echo -e "\nInstalasi Selesai, silahkan ketik: vmess"
